apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cassandra
    spec:
      containers:
      - env:
        - name: HEAP_NEWSIZE
          value: 256M
        - name: MAX_HEAP_SIZE
          value: 1G
        image: cassandra:3.9
        name: cassandra
        ports:
        - containerPort: 9042
        resources: {}
      restartPolicy: Always
status: {}
