apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-claim0
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-claim1
        - mountPath: /var/lib/grafana/dashboards
          name: grafana-claim2
      restartPolicy: Always
      volumes:
      - name: grafana-claim0
        persistentVolumeClaim:
          claimName: grafana-claim0
      - name: grafana-claim1
        persistentVolumeClaim:
          claimName: grafana-claim1
      - name: grafana-claim2
        persistentVolumeClaim:
          claimName: grafana-claim2
status: {}
