apiVersion: v1
kind: Service
metadata:
  name: metrictank-np-service

spec:
  type: NodePort
  ports:
  - name: 2003
    targetPort: 2003
    port: 2003
    nodePort: 32003

  - name: 6060
    targetPort: 6060
    port: 6060
    nodePort: 30066
  selector:
    io.kompose.service: metrictank
