apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: statsdaemon
  name: statsdaemon
spec:
  ports:
  - name: "8125"
    port: 8125
    protocol: UDP
    targetPort: 8125
  selector:
    io.kompose.service: statsdaemon
status:
  loadBalancer: {}
